---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentication-system-post-deploy-job
  namespace: flux-system
spec:
  path: ./authentik/post-deploy-job/jobs
  sourceRef:
    kind: GitRepository
    name: authentik
    namespace: flux-system
  interval: 5m
  prune: true
  wait: true
  dependsOn:
    - name: authentication-system-authentik
      namespace: authentication-system
