---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-cluster
spec:
  description: "PostgreSQL Authentik DB"
  imageName: ${SECRET_HARBOR_URL}/postgresql:16.4
  instances: 2
  bootstrap:
    initdb:
      database: authentik_db
      owner: ${SECRET_AUTHENTIK_PG_USER}
      secret:
        name: authentik-cnpg-user-secret
  storage:
    storageClass: longhorn
    size: 1Gi
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 1
  monitoring:
    enablePodMonitor: true
