---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus-instance: main
  name: authentik-cluster
spec:
  namespaceSelector:
    matchNames:
    - authentication-system
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      postgresql: authentik-cluster