apiVersion: v1
kind: Secret
metadata:
    name: authentik-cnpg-user-secret
    annotations:
        replicator.v1.mittwald.de/replicate-to: monitoring-system,cnpg-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:agLmR7oo8NyaI4X1FaVpFP4NuIOJzBkroW2g,iv:6ouP4uXtTUht1vzrlSG+SRY06odcx2KgtmU1az7jucQ=,tag:DOvzuEV+qZr3VAiigA5t4Q==,type:str]
    password: ENC[AES256_GCM,data:qVzkNNwAt/pDSsNXt4Qjjw0Dg4dcuauv/oGGXKyXBw==,iv:zBmycW7bzxove6WUIVaSoq+GpS8RacG4Tp4vFXsSGHY=,tag:jpVaISDn46tRm4yaAqnLZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdGQ3cjEyNXoydjEzaFpZ
            dGpWV0I1c2hpUElwYjAyVzRzV0s4T1F3WGg0ClF5ZHg3VDVyOFNnZlUwUVNNWUp3
            b1pxTmpKcjhQWjZqb0UrVVdKUjhlencKLS0tIDBIRC9NSE9EVTYzc29jQ1BGaEs1
            ckhCdWRBeXdzaFNIeTI4VmlqL1JYRVUKHoBWCA3QAM07cMQzRWfSNeYatkDAckfl
            PQnOgaxm1EhLaLcUz7O1Lx8LaKUD5d7Tt9cr4L+DGFT1+Xw1kA2tFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T10:14:00Z"
    mac: ENC[AES256_GCM,data:LbzLVCJmVZjqXbgU0btyx5C4WZcoeg24T8tlq/1Tk74dkjTXzub+Y33mRrRvLSfwhDNC1pm/6CUIyQUIB+twI9esRZJH0KdlYQWx4F7TEuY6pbtOq7XTOggJDXh7smySNyOHiMLS+7s146F3/1ohiXOeHjBLvm+fedPOzMbn40M=,iv:R4w1AqdxXFrSKCOiRH9KGO9gM+Zsql0lls21KDWG+HY=,tag:RyA2hE3r85I3fdS3mWWuIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.2
