---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentication-system-authentik
spec:
  path: ./authentik/authentik/base
  sourceRef:
    kind: GitRepository
    name: authentik
    namespace: flux-system
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: traefik-traefik
      namespace: flux-system
    - name: authentication-system-database