---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentication-system
resources:
  - namespace.yaml
  - secret.sops.yaml
  - cloudnativepg/kustomization-fluxCRD.yaml
  - authentik/kustomization-fluxCRD.yaml
  - post-deploy-job/kustomization-fluxCRD.yaml
  # - outpost/kustomization-fluxCRD.yaml