---
apiVersion: batch/v1
kind: Job
metadata:
  name: authentik-user-accounts
  labels:
    name: authentik-user-accounts
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: authentik-user-accounts
          image: debian:12.6-slim
          command: ["/bin/bash", "-c", "/mnt/scripts/createusers.sh"]
          volumeMounts:
          - name: script-volume
            mountPath: /mnt/scripts
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cluster-secret-vars
                  key: SECRET_AUTHENTIK_TOKEN
            - name: USER1_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-secret-vars
                  key: SECRET_AUTHENTIK_USER1_PASSWORD
            - name: USER2_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-secret-vars
                  key: SECRET_AUTHENTIK_USER2_PASSWORD
      initContainers:
      - name: init-permissions
        image: debian:12.6-slim
        command: ["/bin/bash", "-c", "cp /scripts/createusers.sh /mnt/scripts/createusers.sh && chmod +x /mnt/scripts/createusers.sh"]
        volumeMounts:
        - name: users-account-script
          mountPath: /scripts
        - name: script-volume
          mountPath: /mnt/scripts
      volumes:
      - name: users-account-script
        configMap:
          name: users-script-configmap
      - name: script-volume
        emptyDir: {}