apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
stringData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:TqkI1bi+ukmfRgkEeKVfR1LTYttsU/R1GL32Af5HC0tqFJvP94U=,iv:U4bmTZybNkx2eolWQImoq/jPoD/mb7xCwAotcfJl6Sk=,tag:Rc4byYNIuH1cCWsSyT1ndg==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:vtAcHkgTJFAkDeRje7Swhz9q/kKFCjKMVA==,iv:t2IGRUCi0sBJSn6hOBKZY3tE6W+b6QgSrT17nhvN0ZU=,tag:u4Y9eiVDzxScYMfQ/iEvKw==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:OIQ/05ZNu8Zzm+eHdXJjEOQ=,iv:H1p0qUunyrSCiErGLIhHrztlmb+nUaYl+v/94dVqgNw=,tag:GwzlLh2wXPU8xiNbzU7nwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TXB5REEwU1A5Z1BaUy9S
            MmM1OXBDTEhLeU8vbHU1ZDVpb1R3WitOOGtBCnk5T2lGbHNGanBWQStBcmVmNEZQ
            dlVubkR0U0hpY3Rnd0tPSXhmRWJ3SlEKLS0tIDY3Y3J4TGQrU0I5VUJpNXhhanls
            YUEvVlJhNjd6UWQrbXpOdUdSRXNUTWMKpsWUk+NvdKkYVKn+0PsP0EjVS/SWraKF
            0W285lfVbggH6JVe2+m0AZ/xMVxFmaBeekiWsmgNyE9SdCBLyDDjeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T15:01:25Z"
    mac: ENC[AES256_GCM,data:dq6A8W+pG5HK1Od6o1igbzNWHaPnDzHxuqCKpIXEKwwKB9gV9BTIVKSbBALayxS17ZVw6OKU1Jafgh27JNKzYgoQCVBf3u2SQUpNXAHhxxuP8knuY27cwucsmB4+TkSIFFrENcO9vr4ZY0H8xSLmKKn2H4Z6CA/FDsaPaZXnpnI=,iv:e2vRBVToRIFOPsv2vERgC/bEKQqtbGHFfReMoIYeXHg=,tag:1RqPw4/GRLSnzBa+BPvzvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.2
