---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: &app homekube-outpost
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/version: 2024.12.2
  name: authentik-outpost
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: *app
      app.kubernetes.io/managed-by: goauthentik.io
      app.kubernetes.io/name: authentik-proxy
      app.kubernetes.io/version: 2024.12.2
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: *app
        app.kubernetes.io/managed-by: goauthentik.io
        app.kubernetes.io/name: authentik-proxy
        app.kubernetes.io/version: 2024.12.2
    spec:
      containers:
        - name: authproxy
          image: ${SECRET_HARBOR_URL}/authentik-proxy:latest
          env:
            - name: AUTHENTIK_HOST
              valueFrom:
                secretKeyRef:
                  key: authentik_host
                  name: authentik-outpost-api
            - name: AUTHENTIK_HOST_BROWSER
              valueFrom:
                secretKeyRef:
                  key: authentik_host_browser
                  name: authentik-outpost-api
            - name: AUTHENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: authentik-outpost-api
            - name: AUTHENTIK_INSECURE
              valueFrom:
                secretKeyRef:
                  key: authentik_host_insecure
                  name: authentik-outpost-api
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
            - containerPort: 9443
              name: https
              protocol: TCP
          resources: {}
